### ISSUE TITLE
Cannot open load file: No such file or directory, mustache

### ISSUE THREAD

**Issue by vikram-mandyam** [tyler-dodge/org-runbook#1]
Steps: 
1. Install using `use-package`
2. create a runbook.org in a project
3. switch to the project
4. `org-runbook-execute`
5. Error: `Cannot open load file: No such file or directory, mustache`

Environment: 
- Emacs 28.2
- my own config file
- helm completion framework

**Comment by tyler-dodge** [comment]
Thanks for the bug report. 

I think the root cause of this issue is fixed by https://github.com/tyler-dodge/org-runbook/commit/3de6e4e31cd240a2ba128287a3d1bc550c253144

Please reopen if it does not resolve it.
